version: '3'

services:
  Firefox-tests-1:
    image: cypressbase
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/frontend-spec-files/1-quotation-tool/spec-files/quotation-tool.spec.js"]

  Edge-tests-2:
    image: cypressbase
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/backend-spec-files/**/*.spec.js"]

  # Add more services as needed for additional parallelization
Chrome-tests-1:
    image: cypressbase
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/frontend-spec-files/1-quotation-tool/spec-files/quotation-tool.spec.js"]
Webkit-tests-1:
    image: cypressbase
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/frontend-spec-files/1-quotation-tool/spec-files/quotation-tool.spec.js"]
